[package]
name = "univ-csv-stats"
version = "0.1.0"
edition = "2024"

[dependencies]


[workspace]
members = ["core", "bindings/python", "bindings/nodejs"]

[workspace.dependencies]
# Shared dependencies across workspace
anyhow = "1.0"
clap = "4.0"
