[package]
name = "univ-csv-stats-nodejs"
version = "0.1.0"
edition = "2024"

[lib]
name = "univ-csv-stats"
crate-type = ["cdylib"]

[dependencies]
my-project-core = { path = "../../core" }
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
