/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A struct that will be exposed to Node.js as a plain JavaScript object.
 *
 * The `#[napi(object)]` attribute directs `napi-rs` to generate the
 * necessary code to convert this struct to and from a JavaScript object.
 */
export interface SelectedStats {
  count: number
  min: number
  max: number
  sum: number
  mean: number
  variance: number
  standardDeviation: number
  skewness: number
  kurtosis: number
}
/**
 * A Node.js function that calculates statistics from a CSV file.
 *
 * This function wraps the `calculate_stats_from_file` function from the core
 * Rust library. It manually handles the `Result` from the core library.
 * If the core function returns an `Ok`, the stats are converted and returned.
 * If it returns an `Err`, the error is converted into a `napi::Error`, which
 * `napi-rs` will then throw as a JavaScript exception.
 */
export declare function calculateStatsFromFile(path: string): SelectedStats
